name: BillTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test connectivity
        run: curl https://dev.va.gov/status
  
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "https://dev.va.gov/jenkins"
          user: ${{ secrets.API_USER }}
          token: ${{ secrets.API_TOKEN }}
          job: "job/deploys/job/vets-website-vagovdev/build"
#       - name: Run jenkins trigger
#         uses: appleboy/jenkins-action@master
#         with:
#           url: "http://localhost:8080/<some_path>"
#           user: "admin"
#           token: ${{ secrets.TEST_JENKINS_SECRET }}
#           job: "bill-test"
