# name: BillTest

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
#   workflow_dispatch:

# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

# #       - name: Test connectivity
# #         run: curl https://dev.va.gov/jenkins/status
  
#       - name: trigger single Job
#         uses: appleboy/jenkins-action@master
#         with:
#           url: "http://73.167.220.157:8083/jenkins"
#           user: ${{ secrets.LOCAL_API_USER }}
#           token: ${{ secrets.LOCAL_API_TOKEN }}
#           job: "bill-test"
