name: Automatically Create PR
on:
  issues:
    types: [opened, reopened]

jobs:
  create_socks_pull_request:
    if: contains(github.event.issue.labels.*.name, 'ops-access-request')

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: omgitsbillryan/t-lint
          token: ${{ secrets.GIT_API_TOKEN }}

      - name: Read Email Address & SSH Key from Access Request GH Issue
        run: |
          email=$(echo -e "${{ github.event.issue.body }}" | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b" | head -1)
          echo $email
          echo -e "${{ github.event.issue.body }}" | grep -o "\`\`\`.*\`\`\`" | sed 's/`//g' | sed 's/\\r\\n//g'
          echo "email=$email" >> $GITHUB_ENV
          echo "ssh_key=fake_ssh_key" >> $GITHUB_ENV

      # - name: Set foobar to cool
      #   uses: mikefarah/yq@master
      #   with:
      #     cmd: yq e '.key_groups.developers += ["${{env.email}}"]' --inplace config.yml

