name: Request Slack Removal for Offboarding Users
on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
      - name: Check for command
        uses: xt0rted/slash-command-action@v1
        id: command
        with:
          repo-token: ${{ secrets.GIT_API_TOKEN }}
          command: provision_socks
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"

      - name: Split GH Comment CSV into Seperate Variables
        uses: jungwinter/split@v1
        id: split
        with:
          seperator: ", "
          msg: "${{ steps.command.outputs.command-arguments }}"

      - name: Get Token from Github App
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.GH_APP_PEM }}
          APP_ID: ${{ secrets.GH_APP_ID }}

      - name: Get App Installation Token
        run: |
          echo "This token is masked: ${TOKEN}"
        env: 
          TOKEN: ${{ steps.get_token.outputs.app_token }}

      # - name: Update config.yml w/
      #   uses: mikefarah/yq@master
      #   with:
      #     cmd: yq e '.key_groups.$type += [$email]' --inplace config.yml
      #   env:
      #     email: "${{ steps.split.outputs._0 }}"
      #     type: "${{ steps.split.outputs._1 }}"

      # - name: Create /authorized_keys SSH Key File
      #   uses: "finnp/create-file-action@master"
      #   env:
      #     FILE_NAME: "/Users/williamryan/Github/t-lint/ansible/global/config.yml"
          FILE_DATA: "file content"