name: Open SOCKS PR for Requesting department-of-veterans-affairs members

on:
  pull_request:
    branches:
      - master
  # issues:
  #   types: [opened]

jobs:
  open_socks_pr:
    # if: contains(github.event.issue.labels.*.name, 'bill-test-label')

    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Get linked GH Issue Number
        uses: actions/github-script@0.9.0
        id: get_gh_number
        with:
          result-encoding: string
          github-token: ${{secrets.GIT_API_TOKEN}}
          script: |
            let body = context.payload.pull_request.body;
            console.log(context.payload.pull_request.body)

            const patterns = [
              "omgitsbillryan\/t-lint\/issues\/(\\d+)",
              "omgitsbillryan\/t-lint#(\\d+)"
            ];
            const re = new RegExp(patterns.join("|"));

            var match = body.match(re);

            var rtn = "-99";
            if(match) {
              console.log(match);
              match.shift(); // remove match text
              match = match.filter(e => e); // remove 'undefined' values
              console.log(match);
              if(match.length != 1) {
                rtn = "-2"; // means multiple regex matches
              } else {
                rtn = match.toString();
              }
            } else {
              rtn = "-1";
            }

            return rtn;

      - name: Print Result
        run: echo "${{steps.get_gh_number.outputs.result}}"


      # - name: Validate that user is in `bill-test-org` GH Org
      #   uses: octokit/request-action@v2.1.0
      #   id: validate_gh_org_membership
      #   with:
      #     route: GET /orgs/{org}/members/{username}
      #     username: ${{ github.event.sender.login }} # TODO - github.event.issue.owner? github.event.issue.user? get from template instead?
      #     org: bill-test-org
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GIT_API_TOKEN }}

      # - run: |
      #     echo "$RESP"
      #   env:
      #     RESP: ${{ toJson(steps.validate_gh_org_membership.outputs) }}

      # - name: Create PR in `devops` repo