name: Open SOCKS PR for Requesting department-of-veterans-affairs members

on:
  pull_request:
    branches:
      - master
  # issues:
  #   types: [opened]

jobs:
  open_socks_pr:
    # if: contains(github.event.issue.labels.*.name, 'bill-test-label')

    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Get linked GH issue
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GIT_API_TOKEN}}
          script: |
            let body = context.payload.pull_request.body;

            const re1 = /omgitsbillryan\/t-lint\/issues\/(\d+)[\s]/g;
            const matches1 = body.match(re1);
            if(matches1){
              console.log('Matched 1!')
              matches1.forEach(match => {
                console.log(match)
              //  var issueId = match.trim();
              //  let issue = github.issues.get({
              //    owner: 'department-of-veterans-affairs',
              //    repo: 'va.gov-team',
              //    issue_number: issueId,
              //   });
              });
            }

            const re2 = /omgitsbillryan\/t-lint#(\d+)[\s]/g;
            const matches2 = body.match(re2);
            if(matches2){
              console.log('Matched 2!')
              matches2.forEach(match => {
                console.log(match)
              //  var issueId = match.trim();
              //  let issue = github.issues.get({
              //    owner: 'department-of-veterans-affairs',
              //    repo: 'va.gov-team',
              //    issue_number: issueId,
              //   });
              });
            }


      # - name: Validate that user is in `bill-test-org` GH Org
      #   uses: octokit/request-action@v2.1.0
      #   id: validate_gh_org_membership
      #   with:
      #     route: GET /orgs/{org}/members/{username}
      #     username: ${{ github.event.sender.login }} # TODO - github.event.issue.owner? github.event.issue.user? get from template instead?
      #     org: bill-test-org
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GIT_API_TOKEN }}

      # - run: |
      #     echo "$RESP"
      #   env:
      #     RESP: ${{ toJson(steps.validate_gh_org_membership.outputs) }}

      # - name: Create PR in `devops` repo