name: Verify Access Request Issue Owner is a Member of the Org

on:
  pull_request:
    branches:
      - master
  # issues:
  #   types: [opened]

jobs:
  verify_socks_authorization:
    # if: contains(github.event.issue.labels.*.name, 'bill-test-label')

    runs-on: ubuntu-latest
    env:
      owner: omgitsbillryan
      repo: t-lint

    steps:
      - name: Get linked GH Issue Number from PR Body
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GIT_API_TOKEN}}
          script: |
            // -- 1. Get issue number from PR Body --//
            const body = context.payload.pull_request.body;
            const { owner, repo } = process.env

            // GH issue links can take multiple forms
            const patterns = [
              owner + "\/" + repo + "\/issues\/(\\d+)",
              owner + "\/" + repo + "#(\\d+)"
            ];
            const re = new RegExp(patterns.join("|"));

            var match = body.match(re);

            if(!match) throw "No Github Issue Link Found in PR Body!";

            match.shift(); // remove match text
            match = match.filter(e => e); // remove 'undefined' values

            if(match.length != 1) throw "More Than 1 Issue Link Found in PR Body!";


            // -- 2. Get GH Issue -------------------//
            const issue_number = match.toString()
            const issue_resp = await github.issues.get({owner, repo, issue_number})


            // -- 3. Verify GH Org Membership -------//
            const username = issue_resp.data.user.login
            const org = 'bill-test-org' //owner
            const org_resp = await github.orgs.checkMembershipForUser({org, username})

            if(org_resp.status !== 204) throw "Unable to verify user membership to org!"
