name: Open SOCKS PR for Requesting department-of-veterans-affairs members

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GIT_API_TOKEN }}

jobs:
  open_socks_pr:
    if: contains(github.event.issue.labels.*.name, 'bill-test-label')

    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      # - name: Check for existing PR
      - name: Validate that user is in `bill-test-org` GH Org
        uses: octokit/request-action@v2.1.0
        id: validate_gh_org_membership
        with:
          route: GET /orgs/{org}/members/{username} # TODO - github.event.issue.owner? github.event.issue.user? get from template instead?
          username: ${{ github.event.sender.login }}
          org: bill-test-org
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.validate_gh_org_membership.outputs.data }}"

      # - name: Create PR in `devops` repo