name: Open SOCKS PR for Requesting department-of-veterans-affairs members

on:
  pull_request:
    branches:
      - master
  # issues:
  #   types: [opened]

jobs:
  open_socks_pr:
    # if: contains(github.event.issue.labels.*.name, 'bill-test-label')

    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Get linked GH Issue Number from PR Body
        uses: actions/github-script@0.9.0
        id: get_gh_number
        with:
          result-encoding: string
          github-token: ${{secrets.GIT_API_TOKEN}}
          script: |
            let body = context.payload.pull_request.body;

            console.log(context.payload.pull_request)

            throw "Stop!"