name: Open SOCKS PR for Requesting department-of-veterans-affairs members

on:
  pull_request:
    branches:
      - master
  # issues:
  #   types: [opened]

jobs:
  open_socks_pr:
    # if: contains(github.event.issue.labels.*.name, 'bill-test-label')

    runs-on: ubuntu-latest
    env:
      owner: omgitsbillryan
      repo: t-lint
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Get linked GH Issue Number from PR Body
        uses: actions/github-script@v4
        id: get_gh_number
        with:
          result-encoding: string
          github-token: ${{secrets.GIT_API_TOKEN}}
          script: |
            let body = context.payload.pull_request.body;
            const { owner, repo } = process.env

            console.log(`Repo owner = ${owner}`)

            // GH issue links can take multiple forms
            const patterns = [
              owner + "\/" + repo + "\/issues\/(\\d+)",
              owner + "\/" + repo + "#(\\d+)"
            ];
            const re = new RegExp(patterns.join("|"));

            var match = body.match(re);

            if(!match) throw "No Github Issue Link Found in PR Body!";

            match.shift(); // remove match text
            match = match.filter(e => e); // remove 'undefined' values

            if(match.length != 1) throw "More Than 1 Issue Link Found in PR Body!";

            const issue_number = match.toString()
            const issue_resp = await github.issues.get({owner, repo, issue_number})

            const username = issue_resp.data.user.login
            console.log(`username = ${username}`)
            
            const org_resp = await github.orgs.checkMembershipForUser({
                              org: repo,
                              username: username
                            });
            console.log(org_resp)

            return match.toString();

      - name: Print GH Issue Number
        run: echo "${{steps.get_gh_number.outputs.result}}"

      - name: Get the GH Issue
        uses: octokit/request-action@v2.1.0
        id: get_gh_issue
        with:
          route: GET /repos/{owner}/{repo}/issues/{issue_number}
          owner: omgitsbillryan
          repo: t-lint
          issue_number: ${{steps.get_gh_number.outputs.result}}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_API_TOKEN }}

      - name: Print the GET GH Issue Response
        run: echo "user is... ${{ fromJson(steps.get_gh_issue.outputs.data).user.login }}"

      - name: Validate that user is in `bill-test-org` GH Org
        uses: octokit/request-action@v2.1.0
        id: validate_gh_org_membership
        with:
          route: GET /orgs/{org}/members/{username}
          username: ${{ fromJson(steps.get_gh_issue.outputs.data).user.login }} # TODO - github.event.sender.login? github.event.issue.owner? github.event.issue.user? get from template instead?
          org: bill-test-org
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_API_TOKEN }}

      - run: |
          echo "$RESP"
        env:
          RESP: ${{ toJson(steps.validate_gh_org_membership.outputs) }}

      # - name: Create PR in `devops` repo